WARRIOR_MAP = [[
[{
    "sufix": "_3",
    "steps_1": 3,
    "steps_2": 5,
    "steps_3": 7,
    "map_name": "game_place",
    "map_width": 3,
    "map_height": 3,
    "start_x": 1,
    "start_y": -1,
    "finish_x": 2,
    "finish_y": 3,
    "blocks": [{
        "md": 1,
        "mv": true,
        "ch": 0,
        "id": 0,
        "mx": true
    }, {
        "md": 1,
        "mv": true,
        "ch": 0,
        "id": 5,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 0,
        "mx": true
    }, {
        "md": 1,
        "mv": true,
        "ch": 0,
        "id": 0,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 5,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 12,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 0,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 3,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": -1,
        "mx": true
    }]
}, {
    "sufix": "_3",
    "steps_1": 5,
    "steps_2": 7,
    "steps_3": 9,
    "map_name": "game_place",
    "map_width": 3,
    "map_height": 3,
    "start_x": 1,
    "start_y": -1,
    "finish_x": 2,
    "finish_y": 3,
    "blocks": [{
        "md": 1,
        "mv": true,
        "ch": 0,
        "id": 5,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": -1,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 12,
        "mx": true
    }, {
        "md": 1,
        "mv": true,
        "ch": 0,
        "id": 0,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 3,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": -1,
        "mx": true
    }, {
        "md": 2,
        "mv": true,
        "ch": 0,
        "id": 0,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 0,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 5,
        "mx": true
    }]
}, {
    "sufix": "_3",
    "steps_1": 7,
    "steps_2": 9,
    "steps_3": 11,
    "map_name": "game_place",
    "map_width": 3,
    "map_height": 3,
    "start_x": 1,
    "start_y": -1,
    "finish_x": 2,
    "finish_y": 3,
    "blocks": [{
        "md": 1,
        "mv": true,
        "ch": 0,
        "id": 6,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 9,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 0,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": -1,
        "mx": true
    }, {
        "md": 1,
        "mv": true,
        "ch": 0,
        "id": 5,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 12,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 3,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 0,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 10,
        "mx": true
    }]
}, {
    "sufix": "_3",
    "steps_1": 7,
    "steps_2": 9,
    "steps_3": 11,
    "map_name": "game_place",
    "map_width": 3,
    "map_height": 3,
    "start_x": 1,
    "start_y": -1,
    "finish_x": 2,
    "finish_y": 3,
    "blocks": [{
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 0,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 5,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 12,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 3,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": -1,
        "mx": true
    }, {
        "md": 1,
        "mv": true,
        "ch": 0,
        "id": 5,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": -1,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 2,
        "id": 0,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 8,
        "id": 0,
        "mx": true
    }]
}, {
    "sufix": "_3",
    "steps_1": 12,
    "steps_2": 14,
    "steps_3": 16,
    "map_name": "game_place",
    "map_width": 3,
    "map_height": 3,
    "start_x": 1,
    "start_y": -1,
    "finish_x": 2,
    "finish_y": 3,
    "blocks": [{
        "md": 2,
        "mv": true,
        "ch": 0,
        "id": -1,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": -1,
        "mx": true
    }, {
        "md": 1,
        "mv": true,
        "ch": 0,
        "id": 3,
        "mx": true
    }, {
        "md": 2,
        "mv": true,
        "ch": 0,
        "id": 0,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 2,
        "id": 0,
        "mx": true
    }, {
        "md": 1,
        "mv": true,
        "ch": 8,
        "id": 0,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 5,
        "mx": true
    }, {
        "md": 1,
        "mv": true,
        "ch": 0,
        "id": 5,
        "mx": true
    }, {
        "md": 1,
        "mv": true,
        "ch": 0,
        "id": 12,
        "mx": true
    }]
}, {
    "sufix": "_3",
    "steps_1": 12,
    "steps_2": 14,
    "steps_3": 16,
    "map_name": "game_place",
    "map_width": 3,
    "map_height": 3,
    "start_x": 1,
    "start_y": -1,
    "finish_x": 2,
    "finish_y": 3,
    "blocks": [{
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 5,
        "mx": true
    }, {
        "md": 1,
        "mv": true,
        "ch": 0,
        "id": 0,
        "mx": true
    }, {
        "md": 1,
        "mv": true,
        "ch": 0,
        "id": 5,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 3,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 4,
        "id": 0,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": -1,
        "mx": true
    }, {
        "md": 1,
        "mv": true,
        "ch": 0,
        "id": 12,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 1,
        "id": 0,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": -1,
        "mx": true
    }]
}, {
    "sufix": "_3",
    "steps_1": 11,
    "steps_2": 13,
    "steps_3": 15,
    "map_name": "game_place",
    "map_width": 3,
    "map_height": 3,
    "start_x": 1,
    "start_y": -1,
    "finish_x": 2,
    "finish_y": 3,
    "blocks": [{
        "md": 1,
        "mv": true,
        "ch": 0,
        "id": 0,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": -1,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 5,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 3,
        "mx": true
    }, {
        "md": 1,
        "mv": true,
        "ch": 0,
        "id": 5,
        "mx": true
    }, {
        "md": 1,
        "mv": true,
        "ch": 0,
        "id": 12,
        "mx": true
    }, {
        "md": 2,
        "mv": true,
        "ch": 0,
        "id": 0,
        "mx": true
    }, {
        "md": 1,
        "mv": true,
        "ch": 0,
        "id": 0,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 0,
        "mx": true
    }]
}, {
    "sufix": "_3",
    "steps_1": 7,
    "steps_2": 9,
    "steps_3": 11,
    "map_name": "game_place",
    "map_width": 3,
    "map_height": 3,
    "start_x": 1,
    "start_y": -1,
    "finish_x": 2,
    "finish_y": 3,
    "blocks": [{
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 6,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 12,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 9,
        "mx": true
    }, {
        "md": 1,
        "mv": true,
        "ch": 0,
        "id": 3,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": -1,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 4,
        "id": 0,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 3,
        "mx": true
    }, {
        "md": 1,
        "mv": true,
        "ch": 0,
        "id": 12,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 1,
        "id": 0,
        "mx": true
    }]
}, {
    "sufix": "_3",
    "steps_1": 7,
    "steps_2": 9,
    "steps_3": 11,
    "map_name": "game_place",
    "map_width": 3,
    "map_height": 3,
    "start_x": 1,
    "start_y": -1,
    "finish_x": 2,
    "finish_y": 3,
    "blocks": [{
        "md": 1,
        "mv": true,
        "ch": 0,
        "id": 5,
        "mx": true
    }, {
        "md": 1,
        "mv": true,
        "ch": 0,
        "id": 6,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 12,
        "mx": true
    }, {
        "md": 1,
        "mv": true,
        "ch": 0,
        "id": -1,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 9,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 6,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 3,
        "mx": true
    }, {
        "md": 1,
        "mv": true,
        "ch": 0,
        "id": 9,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 5,
        "mx": true
    }]
}, {
    "sufix": "_3",
    "steps_1": 8,
    "steps_2": 10,
    "steps_3": 12,
    "map_name": "game_place",
    "map_width": 3,
    "map_height": 3,
    "start_x": 1,
    "start_y": -1,
    "finish_x": 2,
    "finish_y": 3,
    "blocks": [{
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 6,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": -1,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 12,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 10,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 9,
        "mx": true
    }, {
        "md": 1,
        "mv": true,
        "ch": 0,
        "id": 5,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 3,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 2,
        "id": 0,
        "mx": true
    }, {
        "md": 1,
        "mv": true,
        "ch": 8,
        "id": 0,
        "mx": true
    }]
}, {
    "sufix": "_3",
    "steps_1": 5,
    "steps_2": 7,
    "steps_3": 9,
    "map_name": "game_place",
    "map_width": 3,
    "map_height": 3,
    "start_x": 1,
    "start_y": -1,
    "finish_x": 2,
    "finish_y": 3,
    "blocks": [{
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 3,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 6,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 12,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 4,
        "id": 0,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 3,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": -1,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 1,
        "id": 0,
        "mx": true
    }, {
        "md": 1,
        "mv": true,
        "ch": 0,
        "id": 12,
        "mx": true
    }, {
        "md": 1,
        "mv": true,
        "ch": 0,
        "id": 9,
        "mx": true
    }]
}, {
    "sufix": "_3",
    "steps_1": 8,
    "steps_2": 10,
    "steps_3": 12,
    "map_name": "game_place",
    "map_width": 3,
    "map_height": 3,
    "start_x": 1,
    "start_y": -1,
    "finish_x": 2,
    "finish_y": 3,
    "blocks": [{
        "md": 1,
        "mv": true,
        "ch": 0,
        "id": 9,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 0,
        "mx": true
    }, {
        "md": 1,
        "mv": true,
        "ch": 0,
        "id": 12,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 6,
        "mx": true
    }, {
        "md": 1,
        "mv": true,
        "ch": 0,
        "id": 3,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 5,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 0,
        "mx": true
    }, {
        "md": 1,
        "mv": true,
        "ch": 0,
        "id": -1,
        "mx": true
    }, {
        "md": 1,
        "mv": true,
        "ch": 0,
        "id": 10,
        "mx": true
    }]
}, {
    "sufix": "_3",
    "steps_1": 8,
    "steps_2": 10,
    "steps_3": 12,
    "map_name": "game_place",
    "map_width": 3,
    "map_height": 3,
    "start_x": 1,
    "start_y": -1,
    "finish_x": 2,
    "finish_y": 3,
    "blocks": [{
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 6,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 0,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 9,
        "mx": true
    }, {
        "md": 1,
        "mv": true,
        "ch": 0,
        "id": 3,
        "mx": true
    }, {
        "md": 2,
        "mv": true,
        "ch": 0,
        "id": 0,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 12,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 10,
        "mx": true
    }, {
        "md": 1,
        "mv": true,
        "ch": 0,
        "id": 5,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": -1,
        "mx": true
    }]
}, {
    "sufix": "_3",
    "steps_1": 10,
    "steps_2": 12,
    "steps_3": 14,
    "map_name": "game_place",
    "map_width": 3,
    "map_height": 3,
    "start_x": 1,
    "start_y": -1,
    "finish_x": 2,
    "finish_y": 3,
    "blocks": [{
        "md": 1,
        "mv": true,
        "ch": 0,
        "id": 3,
        "mx": true
    }, {
        "md": 1,
        "mv": true,
        "ch": 0,
        "id": 0,
        "mx": true
    }, {
        "md": 1,
        "mv": true,
        "ch": 0,
        "id": -1,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 0,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 12,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 0,
        "mx": true
    }, {
        "md": 1,
        "mv": true,
        "ch": 0,
        "id": 0,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 5,
        "mx": true
    }, {
        "md": 1,
        "mv": true,
        "ch": 0,
        "id": 5,
        "mx": true
    }]
}, {
    "sufix": "_3",
    "steps_1": 7,
    "steps_2": 9,
    "steps_3": 11,
    "map_name": "game_place",
    "map_width": 3,
    "map_height": 3,
    "start_x": 1,
    "start_y": -1,
    "finish_x": 2,
    "finish_y": 3,
    "blocks": [{
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 6,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 12,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 9,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 3,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 12,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 4,
        "id": 0,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": -1,
        "mx": true
    }, {
        "md": 1,
        "mv": true,
        "ch": 0,
        "id": 3,
        "mx": true
    }, {
        "md": 1,
        "mv": true,
        "ch": 1,
        "id": 0,
        "mx": true
    }]
}, {
    "sufix": "_3",
    "steps_1": 10,
    "steps_2": 11,
    "steps_3": 12,
    "map_name": "game_place",
    "map_width": 3,
    "map_height": 3,
    "start_x": 1,
    "start_y": -1,
    "finish_x": 2,
    "finish_y": 3,
    "blocks": [{
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 6,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 0,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 0,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 3,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 9,
        "mx": true
    }, {
        "md": 1,
        "mv": true,
        "ch": 0,
        "id": 12,
        "mx": true
    }, {
        "md": 1,
        "mv": true,
        "ch": 0,
        "id": 10,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 5,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": -1,
        "mx": true
    }]
}, {
    "sufix": "_3",
    "steps_1": 12,
    "steps_2": 13,
    "steps_3": 14,
    "map_name": "game_place",
    "map_width": 3,
    "map_height": 3,
    "start_x": 1,
    "start_y": -1,
    "finish_x": 2,
    "finish_y": 3,
    "blocks": [{
        "md": 1,
        "mv": true,
        "ch": 0,
        "id": 10,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 6,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 12,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": -1,
        "mx": true
    }, {
        "md": 1,
        "mv": true,
        "ch": 0,
        "id": 9,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 5,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 3,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 2,
        "id": 0,
        "mx": true
    }, {
        "md": 1,
        "mv": true,
        "ch": 8,
        "id": 0,
        "mx": true
    }]
}, {
    "sufix": "_3",
    "steps_1": 10,
    "steps_2": 11,
    "steps_3": 12,
    "map_name": "game_place",
    "map_width": 3,
    "map_height": 3,
    "start_x": 1,
    "start_y": -1,
    "finish_x": 2,
    "finish_y": 3,
    "blocks": [{
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 6,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 0,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 12,
        "mx": true
    }, {
        "md": 1,
        "mv": true,
        "ch": 0,
        "id": 9,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 5,
        "mx": true
    }, {
        "md": 1,
        "mv": true,
        "ch": 0,
        "id": 10,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 3,
        "mx": true
    }, {
        "md": 1,
        "mv": true,
        "ch": 0,
        "id": 0,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": -1,
        "mx": true
    }]
}, {
    "sufix": "_3",
    "steps_1": 8,
    "steps_2": 9,
    "steps_3": 10,
    "map_name": "game_place",
    "map_width": 3,
    "map_height": 3,
    "start_x": 1,
    "start_y": -1,
    "finish_x": 2,
    "finish_y": 3,
    "blocks": [{
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 5,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 3,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": -1,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 4,
        "id": 0,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 5,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 12,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 1,
        "id": 0,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 2,
        "id": 0,
        "mx": true
    }, {
        "md": 1,
        "mv": true,
        "ch": 8,
        "id": 0,
        "mx": true
    }]
}, {
    "sufix": "_3",
    "steps_1": 8,
    "steps_2": 9,
    "steps_3": 10,
    "map_name": "game_place",
    "map_width": 3,
    "map_height": 3,
    "start_x": 1,
    "start_y": -1,
    "finish_x": 2,
    "finish_y": 3,
    "blocks": [{
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 3,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 12,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": -1,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 4,
        "id": 0,
        "mx": true
    }, {
        "md": 1,
        "mv": true,
        "ch": 0,
        "id": 6,
        "mx": true
    }, {
        "md": 1,
        "mv": true,
        "ch": 0,
        "id": 3,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 1,
        "id": 0,
        "mx": true
    }, {
        "md": 1,
        "mv": true,
        "ch": 0,
        "id": 12,
        "mx": true
    }, {
        "md": 0,
        "mv": true,
        "ch": 0,
        "id": 9,
        "mx": true
    }]
  }]
]]

BLOCKS = [[
[{
    "id": 1,
    "path": 10,
    "path_2": 0,
    "chain": 0,
    "block": "bl_000",
    "var": 2
}, {
    "id": 2,
    "path": 0,
    "path_2": 0,
    "chain": 2,
    "block": "bl_001",
    "var": 1
}, {
    "id": 3,
    "path": 0,
    "path_2": 0,
    "chain": 4,
    "block": "bl_002",
    "var": 1
}, {
    "id": 4,
    "path": 9,
    "path_2": 0,
    "chain": 0,
    "block": "bl_003",
    "var": 2
}, {
    "id": 5,
    "path": 12,
    "path_2": 0,
    "chain": 0,
    "block": "bl_004",
    "var": 2
}, {
    "id": 6,
    "path": 3,
    "path_2": 0,
    "chain": 0,
    "block": "bl_005",
    "var": 2
}, {
    "id": 7,
    "path": 5,
    "path_2": 0,
    "chain": 0,
    "block": "bl_006",
    "var": 2
}, {
    "id": 8,
    "path": 6,
    "path_2": 0,
    "chain": 0,
    "block": "bl_007",
    "var": 2
}, {
    "id": 9,
    "path": 0,
    "path_2": 0,
    "chain": 0,
    "block": "bl_008",
    "var": 3
}]
]]